[package]
name = "inventory"
version = "0.1.0"
edition = "2021"

[dependencies]
firebase-rs = "2.2.0"
left-pad = "1.0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.133"
tokio ={ version = "1.41.1", features = ["full"] }
uuid ={ version = "1.11.0", features = ["v4"] }
